FROM thingsboard/tb-web-ui

COPY ui/src/svg/logo_title_white.svg /usr/share/tb-web-ui/web/public/static/36f68b2b2bfda81b4a46fcd2d6f8dead.svg
COPY ui/src/svg/logo_title_white.svg.gz /usr/share/tb-web-ui/web/public/static/36f68b2b2bfda81b4a46fcd2d6f8dead.svg.gz
